services:
  web:
    build: .
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
      feedback-service:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  feedback-service:
    build:
      context: ./src/services/feedback-service
    container_name: feedback_service
    env_file:
      - .env
    ports:
      - 8001:8001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


volumes:
  postgres_db: