# Generated by Django 6.0.2 on 2026-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_user_имя_remove_user_пароль_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=64, verbose_name='Категория')),
                ('name', models.CharField(default='', max_length=64, verbose_name='Название')),
                ('description', models.CharField(default='', max_length=256, verbose_name='Описание')),
                ('address', models.CharField(default='', max_length=128, verbose_name='Адрес')),
            ],
        ),
    ]
