# Generated by Django 6.0.2 on 2026-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='id_name',
            field=models.CharField(default='', max_length=16, verbose_name='ID'),
        ),
    ]
