# Generated by Django 6.0.2 on 2026-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_places_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='places',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
