# Generated by Django 6.0.2 on 2026-05-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_places_dislikes_places_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='image_name',
            field=models.CharField(default='', max_length=128, verbose_name='Название изображения'),
        ),
    ]
